"""Core package for the DwC-A cloud geospatial converter."""

from importlib.metadata import PackageNotFoundError, version

from dwca_cloud_geospatial.bundle import (
    BUNDLE_SCHEMA_VERSION,
    MANIFEST_RELATIVE_PATH,
    OCCURRENCE_SCHEMA_VERSION,
    PROCESSING_METADATA_RELATIVE_PATH,
    REJECTED_RECORDS_RELATIVE_PATH,
    SOURCE_METADATA_RELATIVE_PATH,
    VIEWER_CONTRACT_VERSION,
    BundleMetadataWriteResult,
    BundleWriterOptions,
    build_processing_metadata,
    build_source_metadata,
    write_bundle_metadata,
    write_rejected_records_csv,
)
from dwca_cloud_geospatial.conversion import (
    FLATGEOBUF_FORMAT,
    GEOPARQUET_FORMAT,
    SUPPORTED_OUTPUT_FORMATS,
    ConversionError,
    ConversionOptions,
    ConversionResult,
    convert_dwca_archive,
)
from dwca_cloud_geospatial.flatgeobuf import (
    DEFAULT_FLATGEOBUF_RELATIVE_PATH,
    DEFAULT_GEOPACKAGE_RELATIVE_PATH,
    FLATGEOBUF_PROJECTION_COLUMNS,
    FlatGeobufDependencyError,
    FlatGeobufLargeOutputWarning,
    FlatGeobufWriteResult,
    FlatGeobufWriterOptions,
    FlatGeobufWriterWarning,
    GeoPackageStagedFlatGeobufWriter,
    GeoPackageWriteResult,
    estimate_spatial_index_memory_bytes,
    project_flatgeobuf_record,
    write_flatgeobuf_occurrences,
    write_flatgeobuf_occurrences_via_geopackage,
)
from dwca_cloud_geospatial.geoparquet import (
    BBOX_COLUMN,
    DEFAULT_GEOPARQUET_RELATIVE_PATH,
    GEOPARQUET_LARGE_PROJECTION_COLUMNS,
    GEOPARQUET_PROJECTION_COLUMNS,
    GeoParquetDependencyError,
    GeoParquetWriteResult,
    GeoParquetWriterOptions,
    project_geoparquet_record,
    write_geoparquet_occurrences,
)
from dwca_cloud_geospatial.inspection import inspect_dwca
from dwca_cloud_geospatial.occurrence import (
    OccurrenceRowBatch,
    OccurrenceRowStream,
    OccurrenceReadResult,
    OccurrenceSourceRecord,
    iter_occurrence_rows,
    read_occurrence_rows,
    stream_occurrence_row_batches,
)
from dwca_cloud_geospatial.normalization import (
    NormalizedOccurrenceRecord,
    OccurrenceNormalizationCounts,
    OccurrenceNormalizationResult,
    OccurrenceNormalizationWarning,
    RejectedOccurrenceRecord,
    TypeConversionFailure,
    normalize_occurrence_record,
    normalize_occurrence_record_batch,
    normalize_occurrence_records,
)
from dwca_cloud_geospatial.validation import (
    BundleValidationCheck,
    BundleValidationIssue,
    BundleValidationResult,
    validate_output_bundle,
)

try:
    __version__ = version("dwca-cloud-geospatial")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"

__all__ = [
    "__version__",
    "BUNDLE_SCHEMA_VERSION",
    "BBOX_COLUMN",
    "DEFAULT_FLATGEOBUF_RELATIVE_PATH",
    "DEFAULT_GEOPACKAGE_RELATIVE_PATH",
    "DEFAULT_GEOPARQUET_RELATIVE_PATH",
    "FLATGEOBUF_FORMAT",
    "FLATGEOBUF_PROJECTION_COLUMNS",
    "GEOPARQUET_FORMAT",
    "GEOPARQUET_LARGE_PROJECTION_COLUMNS",
    "GEOPARQUET_PROJECTION_COLUMNS",
    "MANIFEST_RELATIVE_PATH",
    "OCCURRENCE_SCHEMA_VERSION",
    "PROCESSING_METADATA_RELATIVE_PATH",
    "REJECTED_RECORDS_RELATIVE_PATH",
    "SOURCE_METADATA_RELATIVE_PATH",
    "VIEWER_CONTRACT_VERSION",
    "BundleMetadataWriteResult",
    "BundleValidationCheck",
    "BundleValidationIssue",
    "BundleValidationResult",
    "BundleWriterOptions",
    "ConversionError",
    "ConversionOptions",
    "ConversionResult",
    "FlatGeobufDependencyError",
    "FlatGeobufLargeOutputWarning",
    "FlatGeobufWriteResult",
    "FlatGeobufWriterOptions",
    "FlatGeobufWriterWarning",
    "GeoPackageStagedFlatGeobufWriter",
    "GeoPackageWriteResult",
    "GeoParquetDependencyError",
    "GeoParquetWriteResult",
    "GeoParquetWriterOptions",
    "SUPPORTED_OUTPUT_FORMATS",
    "estimate_spatial_index_memory_bytes",
    "inspect_dwca",
    "OccurrenceReadResult",
    "OccurrenceRowBatch",
    "OccurrenceRowStream",
    "OccurrenceSourceRecord",
    "NormalizedOccurrenceRecord",
    "OccurrenceNormalizationCounts",
    "OccurrenceNormalizationResult",
    "OccurrenceNormalizationWarning",
    "RejectedOccurrenceRecord",
    "TypeConversionFailure",
    "build_processing_metadata",
    "build_source_metadata",
    "convert_dwca_archive",
    "iter_occurrence_rows",
    "normalize_occurrence_record",
    "normalize_occurrence_record_batch",
    "normalize_occurrence_records",
    "project_flatgeobuf_record",
    "project_geoparquet_record",
    "read_occurrence_rows",
    "stream_occurrence_row_batches",
    "write_flatgeobuf_occurrences",
    "write_flatgeobuf_occurrences_via_geopackage",
    "write_bundle_metadata",
    "write_geoparquet_occurrences",
    "write_rejected_records_csv",
    "validate_output_bundle",
]
